default_job = "check"

[jobs.build]
command = ["cargo", "build"]
need_stdout = true

[jobs.update-and-build]
command = ["sh", "-c", "cargo update && cargo build"]
need_stdout = true

[jobs.update-and-check]
command = ["sh", "-c", "cargo update && cargo check"]
need_stdout = true
allow_warnings = true
background = false
on_change_strategy = "kill_then_restart"
kill = ["pkill", "-TERM", "-P"]

[keybindings]
b = "job:build"
alt-b = "job:update-and-build"
c = "job:check"
alt-c = "job:update-and-check"
